import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf-8'))

const chars = 'abcdefghijklmnopqrstuvwxyz0123456789'
let suffix = ''
for (let i = 0; i < 4; i++) {
  suffix += chars[Math.floor(Math.random() * chars.length)]
}

const version = `${pkg.version}+${suffix}`
const outPath = path.join(root, 'packages/core/src/version.generated.ts')
const content = `// Auto-generated by scripts/generate-version.mjs — do not edit\nexport const BUILD_VERSION = '${version}'\n`

fs.writeFileSync(outPath, content)
console.log(`Generated version: ${version}`)
